In [1]:
import math

# Number of customers who applied for a housing loan
num_applied = 10

# Number of customers who did not apply for a housing loan
num_not_applied = 7

# Total number of customers
total_customers = num_applied + num_not_applied

# Calculate the probabilities
p_applied = num_applied / total_customers
p_not_applied = num_not_applied / total_customers

# Calculate the entropy
entropy_applied = -p_applied * math.log2(p_applied)
entropy_not_applied = -p_not_applied * math.log2(p_not_applied)

# Calculate the overall entropy
overall_entropy = entropy_applied + entropy_not_applied

print("Overall Entropy:", overall_entropy)


Overall Entropy: 0.9774178175281716


In [2]:
# Location 1
employees_location1 = 695
avg_salary_location1 = 13875
sum_location1 = employees_location1 * avg_salary_location1

# Location 2
employees_location2 = 597
avg_salary_location2 = 17086
sum_location2 = employees_location2 * avg_salary_location2

# Calculate the combined mean
total_employees = employees_location1 + employees_location2
combined_mean = (sum_location1 + sum_location2) / total_employees

print("Combined Arithmetic Mean of Monthly Salary:", combined_mean)


Combined Arithmetic Mean of Monthly Salary: 15358.720588235294


In [9]:
import numpy as np

# Example data
# x = [1, 2, 3, 4, 5]
# y = [2, 4, 6, 8, 10]

x=[1,2,3,4,5]
y=[5,10,15,20,25]
# Calculate correlation coefficient
correlation_coefficient = np.cov(x, y)[0, 1] / (np.std(x) * np.std(y))

print("Correlation Coefficient:", correlation_coefficient)


Correlation Coefficient: 1.2499999999999998


In [12]:
h=[1.7,1.9,1.7,1.9,1.2,1.7]
w=[78.4,45.5,45.5,95.6,39.4,54.5]
y=[31.96,17.22,20.45,31.97,32.02,23.95]

import pandas as pd

df=pd.DataFrame({'H':h,'W':w,'Y':y})
df

H     W      Y
0  1.7  78.4  31.96
1  1.9  45.5  17.22
2  1.7  45.5  20.45
3  1.9  95.6  31.97
4  1.2  39.4  32.02
5  1.7  54.5  23.95

In [15]:
X=df['H']
X
# y=df[y]

0    1.7
1    1.9
2    1.7
3    1.9
4    1.2
5    1.7
Name: H, dtype: float64

In [21]:
import numpy as np

# Prepare the dataset
h = [1.7, 1.9, 1.7, 1.9, 1.2, 1.7]
w = [78.4, 45.5, 45.5, 95.6, 39.4, 54.5]
y = [31.96, 17.22, 20.45, 31.97, 32.02, 23.95]

# Normalize the features
h_normalized = (np.array(h) - np.mean(h)) / np.std(h)
w_normalized = (np.array(w) - np.mean(w)) / np.std(w)

# New data point
new_h = (1.12 - np.mean(h)) / np.std(h)
new_w = (58.29 - np.mean(w)) / np.std(w)

# Calculate distances
distances = np.sqrt((h_normalized - new_h) ** 2 + (w_normalized - new_w) ** 2)

# Identify the K nearest neighbors
k = 3
nearest_indices = np.argsort(distances)[:k]
nearest_bmi = np.array(y)[nearest_indices]

# Determine the predicted BMI
predicted_bmi = np.mean(nearest_bmi)

print("Predicted BMI:", predicted_bmi)


Predicted BMI: 25.473333333333333


In [22]:
h_normalized

array([ 0.07124705,  0.92621165,  0.07124705,  0.92621165, -2.06616445,
        0.07124705])

In [23]:
x=[14,24,18,14,22,17]
y=[2,8,10,5,8,3]

import statistics as sd

sd.variance(x)

16.96666666666667

In [24]:
sd.variance(y)

10

In [25]:
v1=[2,-5,9,8]
v2=[-9,-7,-7,-7]

In [26]:
import numpy as np

v1 = np.array([2, -5, 9, 8])
v2 = np.array([-9, -7, -7, -7])

distance = np.linalg.norm(v1 - v2)

print(distance)


24.61706725018234


In [27]:
import numpy as np

# Define the matrix
matrix = np.array([[-1,-3,3,-1],
                   [2,1,3,1],
                   [-1,-2,1,-3],
                  [-3,-2,2,-1]])

# Calculate the adjoint using the np.linalg.inv() and np.linalg.det() functions
adjoint = np.linalg.inv(matrix) * np.linalg.det(matrix)

print(adjoint)


[[ 15.   1.   4. -26.]
 [-35.  18.  11.  20.]
 [ -4.  16.   3.  11.]
 [ 17.  -7. -28.  -1.]]


In [29]:
A=[[-4,-3,1],[4,-1,1]]



import numpy as np

# Define the matrix
A = np.array([[-4, -3, 1], [4, -1, 1]])

# Perform singular value decomposition
U, S, Vt = np.linalg.svd(A)

# Calculate the product of the largest min(m, n) singular values
largest_singular_values_product = np.prod(S[:min(A.shape)])

print(largest_singular_values_product)


18.0


In [30]:
A.shape

(2, 3)

In [36]:
import pandas as pd 
data = {'Day': ['Dinner', 'Lunch', 'Dinner', 'Dinner', 'Lunch'], 'Time': ['Tue', 'Sun', 'Mon', 'Sun', 'Mon'],'TotBill':[17, 10, 21, 23,24]}

Data=pd.DataFrame(data)
Data
Data.groupby([ 'Day', 'Time'])['Time'].count()

Day     Time
Dinner  Mon     1
        Sun     1
        Tue     1
Lunch   Mon     1
        Sun     1
Name: Time, dtype: int64

In [37]:
Data

Day Time  TotBill
0  Dinner  Tue       17
1   Lunch  Sun       10
2  Dinner  Mon       21
3  Dinner  Sun       23
4   Lunch  Mon       24

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


In [44]:

import copy

X = [5, 4, 3, 2, 1]

y = [7, 8, 9]

z= [x, y]

a=copy.deepcopy(z)

b=copy.copy(z)

x[2] = 6

print('a = ', a, a, 'b', b)

a =  [[14, 24, 6, 14, 22, 17], [7, 8, 9]] [[14, 24, 6, 14, 22, 17], [7, 8, 9]] b [[14, 24, 6, 14, 22, 17], [7, 8, 9]]


In [45]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import PolynomialFeatures

# Define the dataset
x1 = np.array([8.44, 3.21, 4.43, 7.52, 2.88, 1.55])
x2 = np.array([3, 12, 8, 5, 9, 8])
y = np.array([1, 0, 0, 1, 0, 0])

# Create polynomial features
poly = PolynomialFeatures(degree=2)
X = poly.fit_transform(np.column_stack((x1, x2)))

# Build logistic regression model
model = LogisticRegression()
model.fit(X, y)

# Extract the coefficients
coefficients = model.coef_[0]

# Find the coefficient of the term x^2
index = poly.get_feature_names().index('x1^2')
coefficient_x2 = coefficients[index]

# Print the coefficient of x^2
print("Coefficient of x^2:", coefficient_x2)


Coefficient of x^2: -0.14888234202687659


D:\Download\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [46]:
import numpy as np

# Define the eigenvalues of matrix A
eigenvalues = np.array([-3, 9, 5])

# Calculate the determinant of A
determinant_A = np.prod(eigenvalues)

# Calculate the determinant of (A^(-1)).T
determinant_inverse_transpose = 1 / determinant_A

print("Determinant of (A^(-1)).T:", determinant_inverse_transpose)


Determinant of (A^(-1)).T: -0.007407407407407408


In [47]:
np.linalg.det(eigenvalues)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [48]:
determinant_A

-135

In [49]:
import numpy as np

A = np.array([[-8, -1, 4, 6],
              [-10, 1, 4, 6],
              [-5, -1, 1, 6],
              [-3, -1, 4, 1]])

eigenvalues = np.linalg.eigvals(A)
sum_of_eigenvalues = np.sum(eigenvalues)

print("Sum of eigenvalues:", sum_of_eigenvalues)


Sum of eigenvalues: -4.999999999999998


In [50]:
A=[[1,-1,0,1],[1,-7,4,3],[2,-20,12,8],[-2,20,-12,-8]]
v-[5,5,-2,2]

NameError: name 'v' is not defined

In [51]:
import math

def calculate_unit_vector(v):
    magnitude_v = math.sqrt(sum(component**2 for component in v))
    unit_vector = [component / magnitude_v for component in v]
    return unit_vector

# Example usage
v = [5, 5, -2, 2]
unit_vector = calculate_unit_vector(v)

print("Unit vector:", unit_vector)


Unit vector: [0.6565321642986127, 0.6565321642986127, -0.2626128657194451, 0.2626128657194451]


In [56]:
final = ''

x = "Mathematics is essential in many fields"

x_upd = x.split(" ")

x_upd =[elem[::-1] for elem in x_upd]
for elem in x_upd:
    final += elem + ''
print(final)

scitamehtaMsilaitnesseniynamsdleif


In [57]:
df=pd.read_csv('Class/bank_marketing (1).csv')

In [58]:
df.head()

Unnamed: 0  age         job  marital  education default  balance housing  \
0           0   41    services  married    unknown      no       88     yes   
1           1   56  technician  married  secondary      no     1938      no   
2           2   30    services   single  secondary      no      245      no   
3           3   34  management   single   tertiary      no     1396     yes   
4           4   29  technician   single  secondary      no      -13     yes   

  loan   contact  day month  duration  campaign  pdays  previous poutcome  \
0   no  cellular   11   may       105         1    336         2  failure   
1  yes  cellular   26   feb       229         1    192         4  success   
2  yes  cellular    8   jul       187         2     -1         0  unknown   
3   no  cellular   17   jul       630         1     -1         0  unknown   
4   no  cellular   14   may       512         3     -1         0  unknown   

  deposit  
0      no  
1     yes  
2      no  
3      no  
4      no

In [107]:
# df=df.drop(['Unnamed: 0'],axis=1)
df

age  balance  day  duration  campaign  pdays  previous  job_admin.  \
0      41       88   11       105         1    336         2           0   
1      56     1938   26       229         1    192         4           0   
2      30      245    8       187         2     -1         0           0   
3      34     1396   17       630         1     -1         0           0   
4      29      -13   14       512         3     -1         0           0   
...   ...      ...  ...       ...       ...    ...       ...         ...   
5576   48     2235   15       755         2     -1         0           1   
5577   40     -388    4       195         3    340         1           0   
5578   27       91    4       157         6     95        37           0   
5579   46     1568    2       310         1     55         6           0   
5580   39        0    8       503         1     -1         0           0   

      job_blue-collar  job_entrepreneur  ...  month_may  month_nov  month_oct  \
0                   0                 0  ...          1          0          0   
1                   0                 0  ...          0          0          0   
2                   0                 0  ...          0          0          0   
3                   0                 0  ...          0          0          0   
4                   0                 0  ...          1          0          0   
...               ...               ...  ...        ...        ...        ...   
5576                0                 0  ...          1          0          0   
5577                1                 0  ...          1          0          0   
5578                0                 0  ...          0          0          0   
5579                1                 0  ...          0          0          0   
5580                0                 0  ...          1          0          0   

      month_sep  poutcome_failure  poutcome_other  poutcome_success  \
0             0                 1               0                 0   
1             0                 0               0                 1   
2             0                 0               0                 0   
3             0                 0               0                 0   
4             0                 0               0                 0   
...         ...               ...             ...               ...   
5576          0                 0               0                 0   
5577          0                 1               0                 0   
5578          0                 0               1                 0   
5579          0                 0               1                 0   
5580          0                 0               0                 0   

      poutcome_unknown  deposit_no  deposit_yes  
0                    0           1            0  
1                    0           0            1  
2                    1           1            0  
3                    1           1            0  
4                    1           1            0  
...                ...         ...          ...  
5576                 1           1            0  
5577                 0           1            0  
5578                 0           1            0  
5579                 0           0            1  
5580                 1           1            0  

[5581 rows x 53 columns]

In [105]:
df.columns

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'education_primary', 'education_secondary', 'education_tertiary',
       'education_unknown', 'default_no', 'default_yes', 'housing_no',
       'housing_yes', 'loan_no', 'loan_yes', 'contact_cellular',
       'contact_telephone', 'contact_unknown', 'month_apr', 'month_aug',
       'month_dec', 'month_feb', 'month_jan', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'poutcome_failure', 'poutcome_other', 'poutcome_success',
       'poutcome_unknown', 'deposit_no', 'deposit_yes'],
      dtype='object')

In [97]:
unemployed_subscribed = df[(df['job'] == 'unemployed') & (df['deposit'] == 'yes')]
unemployed_subscribed

Unnamed: 0  age         job   marital  education default  balance  \
5              5   26  unemployed    single  secondary      no      632   
10            10   51  unemployed   married  secondary      no     1416   
243          243   26  unemployed    single   tertiary      no      814   
252          252   28  unemployed   married    primary      no     7459   
440          440   56  unemployed   married  secondary      no        0   
...          ...  ...         ...       ...        ...     ...      ...   
5370        5370   37  unemployed    single  secondary      no      381   
5377        5377   31  unemployed   married  secondary      no        6   
5422        5422   48  unemployed  divorced  secondary      no      201   
5464        5464   25  unemployed    single   tertiary      no      343   
5479        5479   37  unemployed   married   tertiary      no     7620   

     housing loan    contact  day month  duration  campaign  pdays  previous  \
5         no   no   cellular   12   feb       218         1     -1         0   
10        no   no   cellular    9   sep       345         1     -1         0   
243       no   no   cellular   28   jan      1387         1     -1         0   
252      yes   no   cellular    2   feb       981         5    269         2   
440       no   no  telephone    2   feb       492         1     -1         0   
...      ...  ...        ...  ...   ...       ...       ...    ...       ...   
5370     yes   no    unknown    8   may       985         2     -1         0   
5377      no   no   cellular    4   jun       121         4     -1         0   
5422      no   no   cellular   10   nov       594         1     91         1   
5464      no   no   cellular    1   jun       377         1     -1         0   
5479      no   no  telephone   23   feb       367         1    176         6   

     poutcome deposit  
5     unknown     yes  
10    unknown     yes  
243   unknown     yes  
252   failure     yes  
440   unknown     yes  
...       ...     ...  
5370  unknown     yes  
5377  unknown     yes  
5422  success     yes  
5464  unknown     yes  
5479  failure     yes  

[92 rows x 18 columns]

In [108]:
df = pd.get_dummies(df)

X=df[['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'education_primary', 'education_secondary', 'education_tertiary',
       'education_unknown', 'default_no', 'default_yes', 'housing_no',
       'housing_yes', 'loan_no', 'loan_yes', 'contact_cellular',
       'contact_telephone', 'contact_unknown', 'month_apr', 'month_aug',
       'month_dec', 'month_feb', 'month_jan', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'poutcome_failure', 'poutcome_other', 'poutcome_success',
       'poutcome_unknown', 'deposit_no', 'deposit_yes']]
y=df['deposit_no']

In [109]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)


In [114]:
from sklearn.neighbors import KNeighborsClassifier

# Assuming X_train and y_train are the feature and target variables in the train dataset
model = KNeighborsClassifier(n_neighbors=3)  # Set the desired number of neighbors
model.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=3)

In [115]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.7331343283582089

In [82]:
df[df['deposit']=='no'].campaign.max()

63

In [67]:
df.duplicated().sum()

0

In [69]:
df.shape

(5581, 17)

In [73]:
import pandas as pd

# Load the dataset into a dataframe
df = pd.read_csv('Class/bank_marketing (1).csv')

# Filter the dataframe for clients who have subscribed to a deposit
subscribed_clients = df[df['deposit'] == 'yes']

# Calculate the average age of subscribed clients
average_age = subscribed_clients['age'].mean()

print("Average age of subscribed clients:", average_age)


Average age of subscribed clients: 41.42677345537757


In [79]:
import pandas as pd

# Load the dataset into a dataframe
# df = pd.read_csv('path_to_dataset.csv')

# Filter the dataframe for clients who have not subscribed to a deposit
not_subscribed_clients = df[df['deposit'] == 'no']

# Find the maximum number of contacts for not subscribed clients
max_contacts = not_subscribed_clients['campaign'].max()

print("Maximum number of contacts for not subscribed clients:", max_contacts)


Maximum number of contacts for not subscribed clients: 63


In [83]:
import pandas as pd

# Load the dataset into a dataframe
# df = pd.read_csv('path_to_dataset.csv')

# Filter the dataframe for clients who have subscribed to a deposit
subscribed_clients = df[df['deposit'] == 'yes']

# Filter the dataframe for clients who have not subscribed to a deposit
not_subscribed_clients = df[df['deposit'] == 'no']

# Find the maximum balance for subscribed clients
max_balance_subscribed = subscribed_clients['balance'].max()

# Find the maximum balance for not subscribed clients
max_balance_not_subscribed = not_subscribed_clients['balance'].max()

# Calculate the difference in maximum balance
difference = max_balance_subscribed - max_balance_not_subscribed

print("Difference in maximum balance (in euros):", difference)


Difference in maximum balance (in euros): 24373
