In [3]:
# Scientific Python

#cube root
from scipy.special import cbrt

cb=cbrt([27,64])
cb

array([3., 4.])

In [7]:
import scipy.special as ss

In [11]:
# exponential
ss.exp10([1,10,3])

array([1.e+01, 1.e+10, 1.e+03])

In [12]:
# Permutations  - nPr = n!/(n-r)!
ss.perm(5,2)

20.0

In [16]:
ss.perm(2,2)

2.0

In [17]:
# combinations

ss.comb(5,2)

10.0

# Linear Algebra

Determinant
inverse
eigen values
eigen vector


In [21]:
# Determinant # ad-bc

import numpy as np
a=np.array([[2,3],[6,4]])

import scipy as sc 
sc.linalg.det(a)

-10.0

In [22]:
# inverse  - adj(a)/det(a)

sc.linalg.inv(a)

array([[-0.4,  0.3],
       [ 0.6, -0.2]])

In [30]:
# Eigen value and eigen vector # mod(A-lambda *I)X=0

eigen_val,eigen_vector=sc.linalg.eig(a)
print(eigen_val,'\n\n\n',eigen_vector)

[-1.35889894+0.j  7.35889894+0.j] 


 [[-0.66613722 -0.48848147]
 [ 0.7458292  -0.87257427]]


In [34]:
# Constants

from scipy import constants

print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', 'gram', 'gravitational_con

In [38]:
print(constants.mebi)
constants.speed_of_light

1048576


299792458.0

In [37]:
print(constants.pi)

3.141592653589793
